# This rule is not used by the project builder-playground-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over builderplayground.flashbots.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: builder-playground-operator
    app.kubernetes.io/managed-by: kustomize
  name: builderplaygrounddeployment-admin-role
rules:
- apiGroups:
  - builderplayground.flashbots.io
  resources:
  - builderplaygrounddeployments
  verbs:
  - '*'
- apiGroups:
  - builderplayground.flashbots.io
  resources:
  - builderplaygrounddeployments/status
  verbs:
  - get
