# This rule is not used by the project builder-playground-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to builderplayground.flashbots.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: builder-playground-operator
    app.kubernetes.io/managed-by: kustomize
  name: builderplaygrounddeployment-viewer-role
rules:
- apiGroups:
  - builderplayground.flashbots.io
  resources:
  - builderplaygrounddeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - builderplayground.flashbots.io
  resources:
  - builderplaygrounddeployments/status
  verbs:
  - get
