apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: builder-playground-sts
  namespace: dev-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: builder-playground-sts
  serviceName: builder-playground-sts
  template:
    metadata:
      labels:
        app: builder-playground-sts
    spec:
      initContainers:
        - name: prepare-artifacts
          image: golang:1.24
          command:
            - sh
            - -c
            - |
              if [ "$(find /artifacts/output -mindepth 1 ! -name 'lost+found' -print -quit 2>/dev/null)" = "" ]; then
                echo "Preparing /artifacts directory..."
                cd src
                git clone https://github.com/flashbots/builder-playground.git
                cd builder-playground
                go clean -cache -modcache
                go mod tidy
                go build -o builder-playground .
                echo "we got binary builder-playground...................."
                ./builder-playground cook l1 \
                  --latest-fork \
                  --use-reth-for-validation \
                  --output /artifacts/output \
                  --genesis-delay 15 \
                  --log-level debug \
                  --dry-run
                echo "after command builder-playground.......move files............."
                mv /artifacts/output/* /artifacts/output/.* /artifacts/ 2>/dev/null
                echo "Data has been generated" > /artifacts/output/data-generated.txt
                echo "complete command builder-playground...................."
              else
                echo "/artifacts/output already exists and is not empty. Skipping preparation."
              fi

          volumeMounts:
            - mountPath: /artifacts
              name: artifacts

      containers:
        - name: debug-artifacts
          image: busybox
          command: ["sh", "-c", "sleep infinity"]
          volumeMounts:
            - mountPath: /artifacts
              name: artifacts
        # - name: prepare-artifacts
        #   image: golang:1.24
        #   command:
        #     - sh
        #     - -c
        #     - |
        #       if [ "$(find /artifacts/output -mindepth 1 ! -name 'lost+found' -print -quit 2>/dev/null)" = "" ]; then
        #         echo "Preparing /artifacts directory..."
        #         cd src
        #         git clone https://github.com/flashbots/builder-playground.git
        #         cd builder-playground
        #         go clean -cache -modcache
        #         go mod tidy
        #         go build -o builder-playground .
        #         echo "we got binary builder-playground...................."
        #         ./builder-playground cook l1 \
        #           --latest-fork \
        #           --use-reth-for-validation \
        #           --output /artifacts/output \
        #           --genesis-delay 15 \
        #           --log-level debug \
        #           --dry-run
        #         echo "after command builder-playground.......move files............."
        #         mv /artifacts/output/* /artifacts/output/.* /artifacts/ 2>/dev/null
        #         echo "Data has been generated" > /artifacts/output/data-generated.txt
        #         echo "complete command builder-playground...................."
        #       else
        #         echo "/artifacts/output already exists and is not empty. Skipping preparation."
        #       fi

        #       sleep infinity
          volumeMounts:
            - mountPath: /artifacts
              name: artifacts


  volumeClaimTemplates:
    - metadata:
        name: artifacts
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
        storageClassName: longhorn