apiVersion: builderplayground.flashbots.io/v1alpha1
kind: BuilderPlaygroundDeployment
metadata:
  name: builder-playground-l1
  namespace: dev-test
spec:
  recipe: l1
  storage:
    type: local-path
    path: /data/builder-playground
  services:
  - name: el
    image: ghcr.io/paradigmxyz/reth
    tag: v1.3.1
    entrypoint:
    - /usr/local/bin/reth
    args:
    - node
    - --chain
    - '/artifacts/genesis.json'
    - --datadir
    - '/artifacts/data_reth'
    - --color
    - never
    - --ipcpath
    - '/artifacts/reth.ipc'
    - --addr
    - 127.0.0.1
    - --port
    - "30303"
    - --http
    - --http.addr
    - 0.0.0.0
    - --http.api
    - admin,eth,web3,net,rpc,mev,flashbots
    - --http.port
    - "8545"
    - --authrpc.port
    - "8551"
    - --authrpc.addr
    - 0.0.0.0
    - --authrpc.jwtsecret
    - '/artifacts/jwtsecret'
    - --metrics
    - 0.0.0.0:9090
    - --engine.persistence-threshold
    - "0"
    - --engine.memory-block-buffer-target
    - "0"
    - -vvvv
    ports:
    - name: rpc
      port: 30303
      protocol: tcp
    - name: http
      port: 8545
      protocol: tcp
    - name: authrpc
      port: 8551
      protocol: tcp
    - name: metrics
      port: 9090
      protocol: tcp
    volumes:
    - name: artifacts
      mountPath: /artifacts
  - name: beacon
    image: sigp/lighthouse
    tag: v7.0.0-beta.0
    entrypoint:
    - lighthouse
    args:
    - bn
    - --datadir
    - '/artifacts/data_beacon_node'
    - --testnet-dir
    - '/artifacts/testnet'
    - --enable-private-discovery
    - --disable-peer-scoring
    - --staking
    - --disable-upnp
    - --disable-optimistic-finalized-sync
    - --disable-discovery
    - --boot-nodes
    - ""
    - --debug-level
    - "error"    
    - --enr-address
    - 127.0.0.1
    - --enr-udp-port
    - "9000"
    - --enr-tcp-port
    - "9000"
    - --enr-quic-port
    - "9100"
    - --port
    - "9000"
    - --quic-port
    - "9100"
    - --http
    - --http-port
    - "3500"
    - --http-address
    - 0.0.0.0
    - --http-allow-origin
    - '*'
    - --disable-packet-filter
    - --target-peers
    - "0"
    - --execution-endpoint
    - http://localhost:8551
    - --execution-jwt
    - '/artifacts/jwtsecret'
    - --always-prepare-payload
    - --prepare-payload-lookahead
    - "8000"
    - --suggested-fee-recipient
    - 0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990
    - --builder
    - http://localhost:5555
    - --builder-fallback-epochs-since-finalization
    - "0"
    - --builder-fallback-disable-checks
    ports:
    - name: p2p-udp
      port: 9000
      protocol: udp
    - name: p2p
      port: 9000
      protocol: tcp
    - name: quic-p2p
      port: 9100
      protocol: tcp
    - name: http
      port: 3500
      protocol: tcp
    readyCheck:
      queryURL: http://localhost:3500/eth/v1/node/syncing
      interval: 1s
      timeout: 30s
      retries: 3
      startPeriod: 1s
    volumes:
    - name: artifacts
      mountPath: /artifacts
  - name: validator
    image: sigp/lighthouse
    tag: v7.0.0-beta.0
    entrypoint:
    - lighthouse
    args:
    - vc
    - --datadir
    - '/artifacts/data_validator'
    - --testnet-dir
    - '/artifacts/testnet'
    - --init-slashing-protection
    - --beacon-nodes
    - http://localhost:3500
    - --suggested-fee-recipient
    - 0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990
    - --builder-proposals
    - --prefer-builder-proposals
    volumes:
    - name: artifacts
      mountPath: /artifacts
  - name: mev-boost
    image: docker.io/flashbots/playground-utils
    tag: latest
    entrypoint:
    - mev-boost-relay
    args:
    - --api-listen-addr
    - 0.0.0.0
    - --api-listen-port
    - "5555"
    - --beacon-client-addr
    - http://localhost:3500
    - --validation-server-addr
    - http://localhost:8545
    env:
      ALLOW_SYNCING_BEACON_NODE: "1"
    ports:
    - name: http
      port: 5555
      protocol: tcp
    dependencies:
    - name: beacon
      condition: healthy
    volumes:
    - name: artifacts
      mountPath: /artifacts